### ISSUE TITLE
Not really an issue, just trying to reach out! 

### ISSUE THREAD

**Issue by mulhollen** [bamajap/AAC-roku-interface#1]
I've been looking to see if there is any community for building applications for Accent 1400 tablets and struggling to come up with anything. I am hoping to be able to maybe get some advice from yourself as it looks like you've delved into this before! I tried to reach out on linkedin but weren't connected enough without premium. If you would have the space to email or have a virtual meeting, my email is lindsaymulhollen@gmail.com. Thanks for your time and hope to hear back :)

**Comment by CrimsonFlameDev** [comment]
Hi Lindsay - really sorry for the delayed response.  I sent you a connect request on LinkedIn.  Let me know here if you did not receive it.  In true GitHub style, I'll close this issue once we have connected. 😉
